### ISSUE TITLE
Compilation failure on SBCL 2.1.1 (DOLIST called on a vector)

### ISSUE THREAD

**Issue by phoe** [nikodemus/screamer#19]
https://github.com/nikodemus/screamer/blob/700359e930e66c8e833e15c83deea6c893f35d1c/screamer.lisp#L5072-L5073

This causes a compilation failure on SBCL 2.1.1 (http://report.quicklisp.org/2021-01-30/failure-report/screamer.html#screamer)

**Comment by nikodemus** [comment]
This is interesting because live code doesn't seem to manage to exercise that branch. Not sure if that's because the tests are sorely lacking or if it's actually dead code.

To replace the compilation warning writing a small DOVECTOR is probably the easiest thing, but I would like to see a test that hits this branch.

**Comment by nikodemus** [comment]
This is resolved by #24, I assume?

**Comment by phoe** [comment]
Yes, it seems so.
